# block 1: imports & sweep config definition
import os
import glob
import time
import torch
from torch.utils.data import DataLoader
from sklearn.model_selection import train_test_split
import wandb as w

from src.data.tumor_dataset import BraTS2DDataset
from src.models.unet_segmentation import UNet
from src.losses.SegmentationLoss import SegmentationLoss
from src.train.train_segmentation import build_slice_indexes, dice_score
import src.config as config



sweep_config = {
    'method': 'bayes',  # Bayesian optimization
    'metric': {
        'name': 'val_dice',
        'goal': 'maximize'
    },
    'early_terminate': {
        'type': 'hyperband',
        'min_iter': 2
    },
    'parameters': {
        'learning_rate': {
            'distribution': 'log_uniform_values',
            'min': 1e-4,
            'max': 1e-2
        },
        'weight_decay': {
            'distribution': 'log_uniform_values',
            'min': 1e-6,
            'max': 1e-3
        },       
        'batch_size': {
            'values': [8, 16, 32]
        }
    }
}

# block 2: sweep execution function
def train_sweep():
    # 1. Bare init() tells WandB to generate a new run and assign hyperparameter values
    w.init()
    
    # 2. Pull the trial hyperparameters generated by WandB for THIS run
    lr = w.config.learning_rate
    wd = w.config.weight_decay
    batch_sz = w.config.batch_size
    sweep_epochs = 5  # Budget limit per trial

    # 3. Build patient splits and slice indices
    patient_dirs = sorted(glob.glob(os.path.join(config.DATA_DIR, "BraTS20_Training_*"), recursive=True))
    train_data, val_data = train_test_split(patient_dirs, test_size=config.VAL_SPLIT, random_state=config.RANDOM_SEED)

    train_loader = DataLoader(
        BraTS2DDataset(build_slice_indexes(train_data)),
        shuffle=True, num_workers=4, pin_memory=True, batch_size=batch_sz
    )
    val_loader = DataLoader(
        BraTS2DDataset(build_slice_indexes(val_data)),
        shuffle=False, num_workers=4, pin_memory=True, batch_size=batch_sz
    )

    # 4. Instantiate model & optimizer with sampled hyperparameters
    model = UNet(in_channels=config.IN_CHANNELS, out_channels=config.OUT_CHANNELS).to(config.DEVICE)
    loss_fn = SegmentationLoss().to(config.DEVICE)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=wd)

    # 5. Execute 5-epoch training loop
    for epoch in range(sweep_epochs):
        epoch_start_time = time.time()
        
        # Training loop
        model.train()
        running_train_loss = 0.0
        for images, masks in train_loader:
            images, masks = images.to(config.DEVICE), masks.to(config.DEVICE)
            optimizer.zero_grad()
            logits = model(images)
            loss = loss_fn(logits, masks)
            loss.backward()
            optimizer.step()
            running_train_loss += loss.item()

        epoch_train_loss = running_train_loss / len(train_loader)

        # Validation loop
        model.eval()
        running_val_loss, running_val_dice = 0.0, 0.0
        with torch.no_grad():
            for images, masks in val_loader:
                images, masks = images.to(config.DEVICE), masks.to(config.DEVICE)
                logits = model(images)
                loss = loss_fn(logits, masks)
                running_val_loss += loss.item()
                running_val_dice += dice_score(logits, masks).item()

        epoch_val_loss = running_val_loss / len(val_loader)
        epoch_val_dice = running_val_dice / len(val_loader)
        epoch_time = time.time() - epoch_start_time
        peak_gpu_mb = torch.cuda.max_memory_allocated() / (1024 ** 2)

        # Log results for Hyperband tracking
        w.log({
            "epoch": epoch + 1,
            "train_loss": epoch_train_loss,
            "val_loss": epoch_val_loss,
            "val_dice": epoch_val_dice,
            "epoch_time_sec": epoch_time,
            "peak_gpu_memory_MB": peak_gpu_mb
        })



# block 3: execution launcher
if __name__ == "__main__":
    sweep_id = w.sweep(sweep_config, project=config.PROJECT_NAME)
    w.agent(sweep_id, function=train_sweep, count=5)